/*
  Auto-generated SQL create+seed from src/mocks/*.js
  Generated at: 2026-03-10T17:38:43.171Z
  SQL dialect: Microsoft SQL Server
*/

SET NOCOUNT ON;

/* mock_customer_master */
/* source: src/mocks/customersFull.js#default */
IF OBJECT_ID(N'dbo.mock_customer_master', N'U') IS NULL
BEGIN
  RAISERROR('Table dbo.mock_customer_master does not exist. Run create script first.', 16, 1);
  RETURN;
END;

DELETE FROM dbo.mock_customer_master;

INSERT INTO dbo.mock_customer_master ([hn], [name], [address], [details], [segment], [discount], [lastVisit], [status])
VALUES
(N'HN001', N'{"prefixTh":"นาย","prefixEn":"Mr.","firstTh":"สมชาย","firstEn":"Somchai","lastTh":"ใจดี","lastEn":"Jaidee","nickname":"ชาย"}', N'{"addressTh":"123 ถนนสุขุมวิท แขวงคลองเตย","addressEn":"123 Sukhumvit Rd., Khlong Toei","provinceTh":"กรุงเทพมหานคร","provinceEn":"Bangkok","postalCode":"10110","districtTh":"คลองเตย","districtEn":"Khlong Toei","subdistrictTh":"คลองเตย","subdistrictEn":"Khlong Toei"}', N'{"genderTh":"ชาย","genderEn":"Male","bloodGroup":"A+","birthDate":"1988-04-12","phone":"081-234-5678","email":"somchai.j@example.com","notes":"ลูกค้าประจำออฟฟิศคลองเตย","age":"37"}', N'ลูกค้าพิเศษ', N'3', CAST('2024-12-19' AS DATE), N'ใช้งาน'),
(N'HN002', N'{"prefixTh":"นางสาว","prefixEn":"Ms.","firstTh":"สุกัญญา","firstEn":"Sukanya","lastTh":"มั่นคง","lastEn":"Mankong","nickname":"กัญ"}', N'{"addressTh":"55 ถ.พระราม 4 แขวงสีลม","addressEn":"55 Rama IV Rd., Silom","provinceTh":"กรุงเทพมหานคร","provinceEn":"Bangkok","postalCode":"10500","districtTh":"บางรัก","districtEn":"Bang Rak","subdistrictTh":"สีลม","subdistrictEn":"Silom"}', N'{"genderTh":"หญิง","genderEn":"Female","bloodGroup":"O+","birthDate":"1992-11-20","phone":"082-345-6789","email":"sukanya.m@example.com","notes":"ชอบนัดวันเสาร์เช้า","age":"33"}', N'ลูกค้า VIP', N'29', CAST('2025-06-09' AS DATE), N'ไม่ใช้งาน'),
(N'HN003', N'{"prefixTh":"นาย","prefixEn":"Mr.","firstTh":"ปรีชา","firstEn":"Preecha","lastTh":"เกษมสุข","lastEn":"Kasemsuk","nickname":"ชา"}', N'{"addressTh":"88 ถ.นิมมานเหมินท์ ต.สุเทพ","addressEn":"88 Nimman Rd., Suthep","provinceTh":"เชียงใหม่","provinceEn":"Chiang Mai","postalCode":"50200","districtTh":"เมืองเชียงใหม่","districtEn":"Mueang Chiang Mai","subdistrictTh":"สุเทพ","subdistrictEn":"Suthep"}', N'{"genderTh":"ชาย","genderEn":"Male","bloodGroup":"B+","birthDate":"1985-07-03","phone":"083-456-7890","email":"preecha.k@example.com","notes":"","age":"40"}', N'ลูกค้าไม่ประจำ', N'7', CAST('2024-12-21' AS DATE), N'ใช้งาน'),
(N'HN004', N'{"prefixTh":"นางสาว","prefixEn":"Ms.","firstTh":"กาญจนา","firstEn":"Kanjana","lastTh":"ประเสริฐ","lastEn":"Prasert","nickname":"จ๋า"}', N'{"addressTh":"12/3 ถ.เทพกระษัตรี ต.ตลาดใหญ่","addressEn":"12/3 Thepkasattri Rd., Talat Yai","provinceTh":"ภูเก็ต","provinceEn":"Phuket","postalCode":"83000","districtTh":"เมืองภูเก็ต","districtEn":"Mueang Phuket","subdistrictTh":"ตลาดใหญ่","subdistrictEn":"Talat Yai"}', N'{"genderTh":"หญิง","genderEn":"Female","bloodGroup":"AB+","birthDate":"1996-02-14","phone":"084-567-8901","email":"kanjana.p@example.com","notes":"ย้ายที่อยู่บ่อย","age":"29"}', N'ลูกค้า VIP', N'28', CAST('2024-11-20' AS DATE), N'ใช้งาน'),
(N'HN005', N'{"prefixTh":"นาย","prefixEn":"Mr.","firstTh":"สมศักดิ์","firstEn":"Somsak","lastTh":"หาญกล้า","lastEn":"Hankla","nickname":"ศักดิ์"}', N'{"addressTh":"199 ถ.สุขุมวิท ต.บางปลาสร้อย","addressEn":"199 Sukhumvit Rd., Bang Pla Soi","provinceTh":"ชลบุรี","provinceEn":"Chon Buri","postalCode":"20000","districtTh":"เมืองชลบุรี","districtEn":"Mueang Chon Buri","subdistrictTh":"บางปลาสร้อย","subdistrictEn":"Bang Pla Soi"}', N'{"genderTh":"ชาย","genderEn":"Male","bloodGroup":"O-","birthDate":"1980-09-18","phone":"085-678-9012","email":"somsak.h@example.com","notes":"","age":"45"}', N'ลูกค้า VIP', N'9', CAST('2025-10-04' AS DATE), N'ใช้งาน'),
(N'HN006', N'{"prefixTh":"นาย","prefixEn":"Mr.","firstTh":"ณัฐวุฒิ","firstEn":"Nattawut","lastTh":"อินทร์ทอง","lastEn":"Inthong","nickname":"วุฒิ"}', N'{"addressTh":"88/9 ถ.ชัยพฤกษ์ ต.บางกระสอ","addressEn":"88/9 Chaiphruek Rd., Bang Krasor","provinceTh":"นนทบุรี","provinceEn":"Nonthaburi","postalCode":"11000","districtTh":"เมืองนนทบุรี","districtEn":"Mueang Nonthaburi","subdistrictTh":"บางกระสอ","subdistrictEn":"Bang Krasor"}', N'{"genderTh":"ชาย","genderEn":"Male","bloodGroup":"A-","birthDate":"1990-01-22","phone":"086-111-2233","email":"nattawut.i@example.com","notes":"","age":"35"}', N'ลูกค้า VIP', N'27', CAST('2025-07-31' AS DATE), N'ไม่ใช้งาน'),
(N'HN007', N'{"prefixTh":"นาง","prefixEn":"Mrs.","firstTh":"วราภรณ์","firstEn":"Waraporn","lastTh":"ทองดี","lastEn":"Thongdee","nickname":"อร"}', N'{"addressTh":"77 หมู่ 4 ต.คลองหนึ่ง","addressEn":"77 Moo 4, Khlong Nueng","provinceTh":"ปทุมธานี","provinceEn":"Pathum Thani","postalCode":"12120","districtTh":"คลองหลวง","districtEn":"Khlong Luang","subdistrictTh":"คลองหนึ่ง","subdistrictEn":"Khlong Nueng"}', N'{"genderTh":"หญิง","genderEn":"Female","bloodGroup":"B-","birthDate":"1983-05-05","phone":"089-222-3344","email":"waraporn.t@example.com","notes":"ลูกค้ากลุ่มครอบครัว","age":"42"}', N'ลูกค้า VIP', N'11', CAST('2025-04-26' AS DATE), N'ใช้งาน'),
(N'HN008', N'{"prefixTh":"นาย","prefixEn":"Mr.","firstTh":"พิชิต","firstEn":"Pichit","lastTh":"สิริชัย","lastEn":"Sirichai","nickname":"ชิต"}', N'{"addressTh":"15 ถ.สุขุมวิท ต.ปากน้ำ","addressEn":"15 Sukhumvit Rd., Pak Nam","provinceTh":"สมุทรปราการ","provinceEn":"Samut Prakan","postalCode":"10270","districtTh":"เมืองสมุทรปราการ","districtEn":"Mueang Samut Prakan","subdistrictTh":"ปากน้ำ","subdistrictEn":"Pak Nam"}', N'{"genderTh":"ชาย","genderEn":"Male","bloodGroup":"AB-","birthDate":"1979-03-29","phone":"080-333-4455","email":"pichit.s@example.com","notes":"","age":"46"}', N'ลูกค้าพิเศษ', N'26', CAST('2025-03-11' AS DATE), N'ไม่ใช้งาน'),
(N'HN009', N'{"prefixTh":"นาย","prefixEn":"Mr.","firstTh":"ธีรศักดิ์","firstEn":"Teerasak","lastTh":"วงศ์วัฒน์","lastEn":"Wongwat","nickname":"ตั้ม"}', N'{"addressTh":"9 ถ.มิตรภาพ ต.ในเมือง","addressEn":"9 Mittraphap Rd., Nai Mueang","provinceTh":"นครราชสีมา","provinceEn":"Nakhon Ratchasima","postalCode":"30000","districtTh":"เมืองนครราชสีมา","districtEn":"Mueang Nakhon Ratchasima","subdistrictTh":"ในเมือง","subdistrictEn":"Nai Mueang"}', N'{"genderTh":"ชาย","genderEn":"Male","bloodGroup":"O+","birthDate":"1987-12-02","phone":"087-444-5566","email":"teerasak.w@example.com","notes":"","age":"38"}', N'ลูกค้าไม่ประจำ', N'13', CAST('2026-01-21' AS DATE), N'ใช้งาน'),
(N'HN010', N'{"prefixTh":"นางสาว","prefixEn":"Ms.","firstTh":"ชลธิชา","firstEn":"Cholticha","lastTh":"ศรีสุวรรณ","lastEn":"Srisuwan","nickname":"มิว"}', N'{"addressTh":"101 ถ.กลางเมือง ต.ในเมือง","addressEn":"101 Klang Muang Rd., Nai Mueang","provinceTh":"ขอนแก่น","provinceEn":"Khon Kaen","postalCode":"40000","districtTh":"เมืองขอนแก่น","districtEn":"Mueang Khon Kaen","subdistrictTh":"ในเมือง","subdistrictEn":"Nai Mueang"}', N'{"genderTh":"หญิง","genderEn":"Female","bloodGroup":"A+","birthDate":"1994-08-09","phone":"086-555-6677","email":"cholticha.s@example.com","notes":"","age":"31"}', N'ลูกค้า VIP', N'25', CAST('2025-09-02' AS DATE), N'ไม่ใช้งาน'),
(N'HN011', N'{"prefixTh":"นาย","prefixEn":"Mr.","firstTh":"นรินทร์","firstEn":"Narin","lastTh":"จันทร์เพ็ญ","lastEn":"Chanphen","nickname":"ริณ"}', N'{"addressTh":"45 ถ.ราชดำเนิน ต.ท่าวัง","addressEn":"45 Ratchadamnoen Rd., Tha Wang","provinceTh":"นครศรีธรรมราช","provinceEn":"Nakhon Si Thammarat","postalCode":"80000","districtTh":"เมืองนครศรีธรรมราช","districtEn":"Mueang Nakhon Si Thammarat","subdistrictTh":"ท่าวัง","subdistrictEn":"Tha Wang"}', N'{"genderTh":"ชาย","genderEn":"Male","bloodGroup":"B+","birthDate":"1982-06-30","phone":"089-666-7788","email":"narin.c@example.com","notes":"","age":"43"}', N'ลูกค้าไม่ประจำ', N'14', CAST('2025-03-27' AS DATE), N'ไม่ใช้งาน'),
(N'HN012', N'{"prefixTh":"นางสาว","prefixEn":"Ms.","firstTh":"พรทิพย์","firstEn":"Porntip","lastTh":"บุญช่วย","lastEn":"Boonchuay","nickname":"พร"}', N'{"addressTh":"12 ถ.ท่าทราย ต.ตลาด","addressEn":"12 Tha Sai Rd., Talat","provinceTh":"สุราษฎร์ธานี","provinceEn":"Surat Thani","postalCode":"84000","districtTh":"เมืองสุราษฎร์ธานี","districtEn":"Mueang Surat Thani","subdistrictTh":"ตลาด","subdistrictEn":"Talat"}', N'{"genderTh":"หญิง","genderEn":"Female","bloodGroup":"AB+","birthDate":"1991-10-17","phone":"082-777-8899","email":"porntip.b@example.com","notes":"ชอบติดต่อทางอีเมล","age":"34"}', N'ลูกค้าประจำ', N'24', CAST('2025-01-16' AS DATE), N'ใช้งาน'),
(N'HN013', N'{"prefixTh":"นาง","prefixEn":"Mrs.","firstTh":"อรทัย","firstEn":"Orathai","lastTh":"สวัสดิ์","lastEn":"Sawas","nickname":"อร"}', N'{"addressTh":"222 ถ.กาญจนวนิช ต.คอหงส์","addressEn":"222 Kanjanavanit Rd., Kho Hong","provinceTh":"สงขลา","provinceEn":"Songkhla","postalCode":"90110","districtTh":"หาดใหญ่","districtEn":"Hat Yai","subdistrictTh":"คอหงส์","subdistrictEn":"Kho Hong"}', N'{"genderTh":"หญิง","genderEn":"Female","bloodGroup":"O+","birthDate":"1986-01-05","phone":"081-888-9900","email":"orathai.s@example.com","notes":"","age":"39"}', N'ลูกค้าพิเศษ', N'16', CAST('2025-09-05' AS DATE), N'ใช้งาน'),
(N'HN014', N'{"prefixTh":"นาย","prefixEn":"Mr.","firstTh":"ศุภกร","firstEn":"Supakorn","lastTh":"มงคลชัย","lastEn":"Mongkolchai","nickname":"กัน"}', N'{"addressTh":"78 ถ.แจ้งสนิท ต.ในเมือง","addressEn":"78 Chaeng Sanit Rd., Nai Mueang","provinceTh":"อุบลราชธานี","provinceEn":"Ubon Ratchathani","postalCode":"34000","districtTh":"เมืองอุบลราชธานี","districtEn":"Mueang Ubon Ratchathani","subdistrictTh":"ในเมือง","subdistrictEn":"Nai Mueang"}', N'{"genderTh":"ชาย","genderEn":"Male","bloodGroup":"A-","birthDate":"1993-03-12","phone":"086-909-0001","email":"supakorn.m@example.com","notes":"","age":"32"}', N'ลูกค้าไม่ประจำ', N'23', CAST('2024-12-06' AS DATE), N'ใช้งาน'),
(N'HN015', N'{"prefixTh":"นาย","prefixEn":"Mr.","firstTh":"กิตติภูมิ","firstEn":"Kittiphum","lastTh":"รัตนชัย","lastEn":"Rattanachai","nickname":"ภูมิ"}', N'{"addressTh":"65 ถ.โพศรี ต.หมากแข้ง","addressEn":"65 Pho Sri Rd., Mak Khaeng","provinceTh":"อุดรธานี","provinceEn":"Udon Thani","postalCode":"41000","districtTh":"เมืองอุดรธานี","districtEn":"Mueang Udon Thani","subdistrictTh":"หมากแข้ง","subdistrictEn":"Mak Khaeng"}', N'{"genderTh":"ชาย","genderEn":"Male","bloodGroup":"B+","birthDate":"1997-09-23","phone":"088-101-2020","email":"kittiphum.r@example.com","notes":"","age":"28"}', N'ลูกค้า VIP', N'17', CAST('2025-05-16' AS DATE), N'ใช้งาน'),
(N'HN016', N'{"prefixTh":"นางสาว","prefixEn":"Ms.","firstTh":"วลัยพร","firstEn":"Walaiporn","lastTh":"วิไลวงศ์","lastEn":"Wilaiwong","nickname":"ไล"}', N'{"addressTh":"19 ถ.พหลโยธิน ต.รอบเวียง","addressEn":"19 Phahonyothin Rd., Rob Wiang","provinceTh":"เชียงราย","provinceEn":"Chiang Rai","postalCode":"57000","districtTh":"เมืองเชียงราย","districtEn":"Mueang Chiang Rai","subdistrictTh":"รอบเวียง","subdistrictEn":"Rob Wiang"}', N'{"genderTh":"หญิง","genderEn":"Female","bloodGroup":"AB-","birthDate":"1995-12-31","phone":"089-303-4040","email":"walaiporn.w@example.com","notes":"","age":"30"}', N'ลูกค้า VIP', N'22', CAST('2025-09-01' AS DATE), N'ใช้งาน'),
(N'HN017', N'{"prefixTh":"นาย","prefixEn":"Mr.","firstTh":"ปวริศ","firstEn":"Pawarit","lastTh":"กาญจนชัย","lastEn":"Kanchanachai","nickname":"ริศ"}', N'{"addressTh":"333 ถ.สุขุมวิท ต.ท่าประดู่","addressEn":"333 Sukhumvit Rd., Tha Pradu","provinceTh":"ระยอง","provinceEn":"Rayong","postalCode":"21000","districtTh":"เมืองระยอง","districtEn":"Mueang Rayong","subdistrictTh":"ท่าประดู่","subdistrictEn":"Tha Pradu"}', N'{"genderTh":"ชาย","genderEn":"Male","bloodGroup":"O+","birthDate":"1984-08-08","phone":"081-505-6060","email":"pawarit.k@example.com","notes":"","age":"41"}', N'ลูกค้าไม่ประจำ', N'19', CAST('2025-11-19' AS DATE), N'ใช้งาน'),
(N'HN018', N'{"prefixTh":"นาง","prefixEn":"Mrs.","firstTh":"จิราภรณ์","firstEn":"Jiraporn","lastTh":"ธรรมรักษ์","lastEn":"Thammarak","nickname":"จิ"}', N'{"addressTh":"12 ถ.ราชดำเนิน ต.พระปฐมเจดีย์","addressEn":"12 Ratchadamnoen Rd., Phra Pathom Chedi","provinceTh":"นครปฐม","provinceEn":"Nakhon Pathom","postalCode":"73000","districtTh":"เมืองนครปฐม","districtEn":"Mueang Nakhon Pathom","subdistrictTh":"พระปฐมเจดีย์","subdistrictEn":"Phra Pathom Chedi"}', N'{"genderTh":"หญิง","genderEn":"Female","bloodGroup":"A+","birthDate":"1978-04-04","phone":"082-606-7070","email":"jiraporn.t@example.com","notes":"","age":"47"}', N'ลูกค้าไม่ประจำ', N'20', CAST('2025-09-01' AS DATE), N'ใช้งาน'),
(N'HN019', N'{"prefixTh":"นาย","prefixEn":"Mr.","firstTh":"พนม","firstEn":"Phanom","lastTh":"อยุธยา","lastEn":"Ayutthaya","nickname":"นม"}', N'{"addressTh":"90 ถ.อู่ทอง ต.ประตูชัย","addressEn":"90 U Thong Rd., Pratu Chai","provinceTh":"พระนครศรีอยุธยา","provinceEn":"Phra Nakhon Si Ayutthaya","postalCode":"13000","districtTh":"พระนครศรีอยุธยา","districtEn":"Phra Nakhon Si Ayutthaya","subdistrictTh":"ประตูชัย","subdistrictEn":"Pratu Chai"}', N'{"genderTh":"ชาย","genderEn":"Male","bloodGroup":"B+","birthDate":"1981-06-16","phone":"083-707-8080","email":"phanom.a@example.com","notes":"","age":"44"}', N'ลูกค้า VIP', N'20', CAST('2026-03-10' AS DATE), N'ไม่ใช้งาน'),
(N'HN020', N'{"prefixTh":"นางสาว","prefixEn":"Ms.","firstTh":"กมลพร","firstEn":"Kamonporn","lastTh":"สุขใจ","lastEn":"Sukjai","nickname":"กมล"}', N'{"addressTh":"18 ถ.เศรษฐกิจ ต.มหาชัย","addressEn":"18 Setthakit Rd., Mahachai","provinceTh":"สมุทรสาคร","provinceEn":"Samut Sakhon","postalCode":"74000","districtTh":"เมืองสมุทรสาคร","districtEn":"Mueang Samut Sakhon","subdistrictTh":"มหาชัย","subdistrictEn":"Mahachai"}', N'{"genderTh":"หญิง","genderEn":"Female","bloodGroup":"O+","birthDate":"1999-02-28","phone":"084-808-9090","email":"kamonporn.s@example.com","notes":"เพิ่งย้ายงาน","age":"26"}', N'ลูกค้าประจำ', N'19', CAST('2025-05-17' AS DATE), N'ใช้งาน');

